### ISSUE TITLE
renku init cleanup

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-python#1121]
The `renku init` options are confusing, we should better define them.
In the design meeting, we agreed on:

1. Changing the output of `--print-manifest` to have these columns:
	* `INDEX`: template position in the `manifest.yaml`
	* `ID`: folder
	* `DESCRIPTION`: combination of `{name}: {description}` from `manifest.yaml`
2. Remove the ambiguous `--template` and add `--template-index` and `--template-id` instead
3. `--print-manifest` is not inuitive. What about `--show-templates` or `--list-templates`? 

We should also better handle the variables to be provided when initializing from a template (needed for the UI). This is the proposal we didn't discuss thoroughly:

4. Include template's available variables in the `manifest.yaml` with a short description
  ```
- folder: python-cuda
  variables:
    - description: a short description going in the Readme file
    - cuda-version: specify cuda version (only 9.x or 10.x)
 ```
This may lead to:
* Print the variables list in `--print-manifest`
* Remove `--description` (currently not used) since there is no need to have it as a special variable
* Rename `--template-variables` to `--variables`
* [bonus]: when some variables are required but not specified, interactively ask them to the user
