### ISSUE TITLE
Still having problems with renku update

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-python#200]
After a successful `renku run papermill..` with the following inputs: the input notebook, the name of the output notebook, and the file with the set of parameters, I modify the input notebook in such a way that the output should change. But then `renku update papermill` prompts the following

```
Error collecting output for parameter 'output_0':
.renku/workflow/71283416484d4b3e8ff74ea80adb06a2_papermill.cwl:40:7: Did not find output file with glob pattern: '['data/AB1893/20026524/20026524_db.xml']'
```

Thus, still the same error with `renku update`

**Comment by jirikuncar** [comment]
@lusamino can you check if the file exists in the temporary directory created by `cwltool` runner? If you are not sure where to look please paste the whole output of `renku update` so I can point you at correct line. Thanks!

**Comment by jirikuncar** [comment]
You should check the temporary folder created by `papermill` (`/private/var/folders/tt/7kty8hcd45d8ytww29d4h4xr0000gn/T/tmpch7bn852`).

**Comment by lusamino** [comment]
So, the only files in that folder are: `3_out.ipynb` and `file_metacorr.xml`, out of the following outputs:

```
  output_0:
    outputBinding:
      glob: data/AB1893/20026524/20026524_db.xml
    streamable: false
    type: File
  output_1:
    outputBinding:
      glob: data/AB1893/20026524/20026524_db.pdf
    streamable: false
    type: File
  output_2:
    outputBinding:
      glob: file_metacorr.xml
    streamable: false
    type: File
  output_3:
    outputBinding:
      glob: 3_out.ipynb
    streamable: false
    type: File
```
I have also tried generating all the files to root:
```
outputs:
  output_0:
    outputBinding:
      glob: file_db.pdf
    streamable: false
    type: File
  output_1:
    outputBinding:
      glob: file_metacorr.xml
    streamable: false
    type: File
  output_2:
    outputBinding:
      glob: 3_out.ipynb
    streamable: false
    type: File
  output_3:
    outputBinding:
      glob: file_db.xml
    streamable: false
    type: File
```

and in that case it worked.
