### ISSUE TITLE
update ci for projects

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#207]
we should update the CI to work with the image build setup (see https://github.com/SwissDataScienceCenter/renku/pull/260). This should include:

`.gitlab-ci.yml`:

```
stages:
  - build

image_build:
  stage: build
  image: python:3.6
  before_script:
    - curl -sSL https://get.docker.com/ | sh
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script:
    - CI_COMMIT_SHA_7=$(echo $CI_COMMIT_SHA | cut -c1-7)
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7 .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA_7
  tags:
    - image-build

dot:
  stage: build
  image: renku/renku-python:latest
  script:
    - python -c "import renku, networkx; graph = renku.cli._graph.Graph(renku.LocalClient()); graph.build_status(); networkx.drawing.nx_pydot.write_dot(graph.G, 'graph.dot')"
  artifacts:
    paths:
      - graph.dot
  environment:
    name: dot/$CI_COMMIT_REF_NAME
    url: $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/raw/graph.dot?job=$CI_JOB_NAME
```

`Dockerfile`:

```
FROM renku/singleuser:latest

COPY requirements.txt /tmp/requirements.txt

COPY src /code/src

WORKDIR /code

USER 0

RUN pip install -r /tmp/requirements.txt

USER 1000
```

a blank `requirements.txt`
