### ISSUE TITLE
set CI variables

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#259]
There are a few variables that should be added for fine-tuning the gitlab-ci builds:

```yaml
variables:
  GIT_STRATEGY: clone
  GIT_SSL_NO_VERIFY: "true"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_LFS_SKIP_SMUDGE: 1
```

Once this is done, the gitlab-ci in `renku-ui` should also be changed.
