### ISSUE TITLE
Composed workflow failing triple generation: Missing default value

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-python#2886]
**Describe the bug**

When running a composed workflow and then forking the project, the file lineage is lost in the fork.
This seems to be caused by `None` default values in mapped parameters of the composed workflow.

This was first observed in [cyril.matthey-doret/digirhythm-demo](https://renkulab.io/projects/cyril.matthey-doret/digirhythm-demo), where lineage is available for [data/digirhythm_panels.png](https://renkulab.io/projects/cyril.matthey-doret/digirhythm-demo/files/lineage/data/digirhythm_panels.png), while the forks show no lineage, e.g. [cmd-test-group/digirhythm-demo](https://renkulab.io/projects/cmd-test-group/digirhythm-demo/files/lineage/data/digirhythm_panels.png).

@jachro looked into what happened in this project and found a problem with triple generation:

```
Error: Validation Report; 
Conforms: False; 
Results (5):; 
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):; 
Severity: sh:Violation; 
Source Shape: [ sh:datatype xsd:string ; 
sh:maxCount Literal("1", datatype=xsd:integer) ; 
sh:minCount Literal("1", datatype=xsd:integer) ; 
sh:nodeKind sh:Literal ; 
sh:path schema:defaultValue ]; 
Focus Node: <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/date-range>; 
Result Path: schema:defaultValue; 
Message: Less than 1 values on <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/date-range>->schema:defaultValue; 
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):; 
Severity: sh:Violation; 
Source Shape: [ sh:datatype xsd:string ; 
sh:maxCount Literal("1", datatype=xsd:integer) ; 
sh:minCount Literal("1", datatype=xsd:integer) ; 
sh:nodeKind sh:Literal ; 
sh:path schema:defaultValue ]; 
Focus Node: <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/activity-col>; 
Result Path: schema:defaultValue; 
Message: Less than 1 values on <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/activity-col>->schema:defaultValue; 
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):; 
Severity: sh:Violation; 
Source Shape: [ sh:datatype xsd:string ; 
sh:maxCount Literal("1", datatype=xsd:integer) ; 
sh:minCount Literal("1", datatype=xsd:integer) ; 
sh:nodeKind sh:Literal ; 
sh:path schema:defaultValue ]; 
Focus Node: <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/input-activity>; 
Result Path: schema:defaultValue; 
Message: Less than 1 values on <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/input-activity>->schema:defaultValue; 
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):; 
Severity: sh:Violation; 
Source Shape: [ sh:datatype xsd:string ; 
sh:maxCount Literal("1", datatype=xsd:integer) ; 
sh:minCount Literal("1", datatype=xsd:integer) ; 
sh:nodeKind sh:Literal ; 
sh:path schema:defaultValue ]; 
Focus Node: <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/output-figure>; 
Result Path: schema:defaultValue; 
Message: Less than 1 values on <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/output-figure>->schema:defaultValue; 
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):; 
Severity: sh:Violation; 
Source Shape: [ sh:datatype xsd:string ; 
sh:maxCount Literal("1", datatype=xsd:integer) ; 
sh:minCount Literal("1", datatype=xsd:integer) ; 
sh:nodeKind sh:Literal ; 
sh:path schema:defaultValue ]; 
Focus Node: <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/sampling>; 
Result Path: schema:defaultValue; 
Message: Less than 1 values on <https://renkulab.io/plans/3ccde8579c724acd8776ae4f3053626c/mappings/sampling>->schema:defaultValue; 
```

This is what the plan looks like for 3ccde8579c724acd8776ae4f3053626c:

```yaml
d: /plans/3ccde8579c724acd8776ae4f3053626c
Name: process-sample
Full processing of a single sample. From raw activity data to figures                                          
Steps: 
        - clean-sample:
                Id: /plans/d8526a769f964ac09caf3f794c4019aa
        - viz-sample:
                Id: /plans/077d5b4d4d19489cadddbccafed09356
Mappings: 
        - output-figure:
                Default Value: None
        Maps to: 
                output-6
        - input-activity:
                Default Value: None
        Maps to: 
                input-2
        - activity-col:
                Default Value: None
        Maps to: 
                act-col-4
        - sampling:
                Default Value: None
        Maps to: 
                sampling-3
        - date-range:
                Default Value: None
        Maps to: 
                date-range-2
Links: 
        - From: clean-sample.output-3
                 To: 
                - viz-sample.input-5
```

**Link to project**

**EDIT**: I am unable to reproduce the issue. The lineage just appeared in the minimal example below. There is probably something wrong with plan 3ccde8579c724acd8776ae4f3053626c

I reproduced the bug in a minimal repository:
* [Original](https://dev.renku.ch/projects/cyril.mattheydoret/renku-compose-original/files/lineage/firstn.txt): contains a composed workflow producing `firstn.txt`. Lineage is available
* [Forked](https://dev.renku.ch/projects/cyril.mattheydoret/renku-compose-forked/files/lineage/firstn.txt):  After forking, the lineage for `firstn.txt` is lost
Commands used to build the workflows listed in [wf_commands.sh](https://dev.renku.ch/projects/cyril.mattheydoret/renku-compose-original/files/blob/wf_commands.sh)
**To Reproduce**
1. Create a project
2. Create a project with a composed workflow
3. Fork it
4. See missing lineage in the fork

**Expected behavior**
Lineage is available in forks
