### ISSUE TITLE
Renku run does not parse some cli files

### ISSUE THREAD

**Issue by KevinSayers** [SwissDataScienceCenter/renku-python#521]
Some cli files are not parsed as being files seemingly depending on how they are specified on the cli.

Example:
```
renku run picard SortSam INPUT=mapped.sam OUTPUT=data/sortedreads.bam SORT_ORDER=coordinate
```
Generates the below incorrect CWL as the type is listed as `string` and not `file`
```
inputs:
  input_1:
    default: INPUT=mapped.sam
    inputBinding:
      position: 1
      separate: true
      shellQuote: true
    streamable: false
    type: string
```
